{
  "hash": "cba086baee1a86229787a63c832a13af",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Regression Models and Analysis of Variance\"\nauthor: \"Michał Janiga\"\n---\n\n\n::: {.cell}\n\n:::\n\n\n# Analysis of Variance (ANOVA) for Exchange Rates\n\nFor the closing rate of the Euro (EURPLN):  \n- Draw box plots illustrating the exchange rate distributions for the last six months of 2025 (separately for each month from July to December 2025).  \n- Using the analysis of variance method, verify the hypothesis of equality of the mean exchange rates across these six months. Comment on the obtained results.  \n- Perform a post-hoc analysis of deviations from the mean using Tukey's and Bonferroni's methods. Comment on the obtained results.  \n- Conduct tests comparing the mean exchange rates across these six months without assuming normality of their distributions. Comment on the obtained results.  \n\n## Data Preparation and Retrieval\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Helper function to load data from stooq.pl\nread_rates <- function(symbol, dateStart, dateEnd) {\n  if (file.exists(\".env\")) readRenviron(\".env\")\n  apiKey <- Sys.getenv(\"STOOQ_API_KEY\")\n  \n  # Formatting dates to the YYYYMMDD format required by the stooq API\n  d1 <- format(dateStart, \"%Y%m%d\")\n  d2 <- format(dateEnd, \"%Y%m%d\")\n  \n  webLink <- paste0('https://stooq.pl/q/d/l/?s=', symbol, \n                    '&i=d&d1=', d1, '&d2=', d2, '&apikey=', apiKey)\n  \n  fileName <- paste0('data/', symbol, '_', d1, '_', d2, '.csv')\n  if (!file.exists(fileName)) {\n    download.file(webLink, fileName, quiet = TRUE)\n  }\n  \n  df_symbol <- read.csv(fileName)\n  # Map Polish column headers to English for consistency\n  names(df_symbol)[names(df_symbol) == \"Data\"] <- \"Date\"\n  names(df_symbol)[names(df_symbol) == \"Zamkniecie\"] <- \"Close\"\n  df_symbol$Date <- as.Date(df_symbol$Date)\n  \n  # Optional local filtering for certainty\n  df_symbol <- df_symbol[which(df_symbol$Date >= dateStart & df_symbol$Date <= dateEnd),]\n  \n  df_symbol <- subset(df_symbol, select = c(Date, Close))\n  names(df_symbol) <- c('Date', symbol)\n  df_symbol\n}\n\n# Fetching data for EURPLN (July - December 2025)\ndateStart <- as.Date(\"2025-07-01\")\ndateEnd <- as.Date(\"2025-12-31\")\ndf_eur <- read_rates('EURPLN', dateStart, dateEnd)\n\n# Data preparation - adding a column with the month number for grouping\ndf_eur$Month <- format(df_eur$Date, \"%m\")\n```\n:::\n\n\n## Box Plots\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Box plots for individual months\nboxplot(EURPLN ~ Month, data = df_eur, \n        main = \"EURPLN exchange rate distribution in the 2nd half of 2025\",\n        xlab = \"Month\", ylab = \"Closing rate [PLN]\",\n        names = c(\"Jul\", \"Aug\", \"Sep\", \"Oct\", \"Nov\", \"Dec\"),\n        col = \"lightblue\")\ngrid()\n```\n\n::: {.cell-output-display}\n![](lab4_files/figure-html/unnamed-chunk-3-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n## Analysis of Variance (ANOVA)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Conducting the Analysis of Variance (ANOVA)\naov_res <- aov(EURPLN ~ Month, data = df_eur)\nsummary(aov_res)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Df  Sum Sq  Mean Sq F value Pr(>F)    \nMonth         5 0.02364 0.004728   51.27 <2e-16 ***\nResiduals   125 0.01153 0.000092                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\ntab_anova <- summary(aov_res)[[1]]\np_raw <- tab_anova[\"Month\", \"Pr(>F)\"]\np_value <- format.pval(p_raw, eps = 0.001, digits = 3)\n```\n:::\n\n\n**Comment:** The obtained p-value $Pr(>F) <0.001$ is significantly smaller than the assumed significance level $\\alpha = 0.05$. This provides a solid basis to reject the null hypothesis of equal mean EURPLN exchange rates in the analyzed months (July–December 2025). This result indicates that the mean exchange rates of the currency in the studied periods differed from one another in a statistically significant way. The extremely high F-statistic value confirms that the month is a factor that strongly differentiates the level of the closing exchange rate. To determine precisely which months differ from each other, a post-hoc analysis (e.g., Tukey's test) must be conducted.\n\n## Post-Hoc Analysis (Tukey and Bonferroni)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Tukey's HSD method\ntukey_res <- TukeyHSD(aov_res)\nprint(tukey_res)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Tukey multiple comparisons of means\n    95% family-wise confidence level\n\nFit: aov(formula = EURPLN ~ Month, data = df_eur)\n\n$Month\n              diff          lwr          upr     p adj\n08-07  0.004397660 -0.003990956  0.012786277 0.6537979\n09-07  0.002453202 -0.005835158  0.010741561 0.9558889\n10-07 -0.007185217 -0.015380966  0.001010531 0.1212538\n11-07 -0.018106435 -0.026603968 -0.009608902 0.0000001\n12-07 -0.033689526 -0.041977885 -0.025401167 0.0000000\n09-08 -0.001944459 -0.010423579  0.006534662 0.9855265\n10-08 -0.011582878 -0.019971494 -0.003194261 0.0014979\n11-08 -0.022504095 -0.031187796 -0.013820395 0.0000000\n12-08 -0.038087186 -0.046566307 -0.029608066 0.0000000\n10-09 -0.009638419 -0.017926778 -0.001350060 0.0127134\n11-09 -0.020559636 -0.029146526 -0.011972747 0.0000000\n12-09 -0.036142727 -0.044522673 -0.027762781 0.0000000\n11-10 -0.010921217 -0.019418751 -0.002423684 0.0039818\n12-10 -0.026504308 -0.034792667 -0.018215949 0.0000000\n12-11 -0.015583091 -0.024169980 -0.006996202 0.0000092\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(tukey_res, las = 1)\n```\n\n::: {.cell-output-display}\n![](lab4_files/figure-html/unnamed-chunk-5-1.png){fig-align='center' width=672}\n:::\n\n```{.r .cell-code}\n# Bonferroni correction method\nbonf_res <- pairwise.t.test(df_eur$EURPLN, df_eur$Month, p.adj = 'bonf')\nprint(bonf_res)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPairwise comparisons using t tests with pooled SD \n\ndata:  df_eur$EURPLN and df_eur$Month \n\n   07      08      09      10      11     \n08 1.0000  -       -       -       -      \n09 1.0000  1.0000  -       -       -      \n10 0.1859  0.0016  0.0152  -       -      \n11 1.3e-07 1.5e-10 3.0e-09 0.0045  -      \n12 < 2e-16 < 2e-16 < 2e-16 1.1e-14 9.4e-06\n\nP value adjustment method: bonferroni \n```\n\n\n:::\n:::\n\n\n**Comment:** The post-hoc analysis using Tukey's and Bonferroni's methods yields highly consistent results and allows for a precise identification of month pairs between which significant differences occurred. The tests confirm that the summer months (July, August, September) form a cluster with a similar exchange rate level (no significant differences, Bonferroni p-value equal to 1.000). Significant shifts begin in October (which differs significantly from August and September). In turn, November and December differ in a highly significant manner (p < 0.001) from all preceding months. These findings, combined with the negative mean differences observed in Tukey's test, clearly document a downward trend in the EURPLN rate (appreciation of the Polish złoty) across the entire studied half-year. Tukey's plot visualizes this trend, as the majority of confidence intervals are shifted to the left of the zero line.\n\n## Kruskal-Wallis Test (Without Assuming Normality)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Conducting the Kruskal-Wallis test\nkruskal_res <- kruskal.test(EURPLN ~ Month, data = df_eur)\nprint(kruskal_res)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKruskal-Wallis rank sum test\n\ndata:  EURPLN by Month\nKruskal-Wallis chi-squared = 79.224, df = 5, p-value = 1.22e-15\n```\n\n\n:::\n:::\n\n\n**Comment:** The Kruskal-Wallis test result is fully consistent with the ANOVA findings. The extremely low p-value allows us to reject the null hypothesis of equal EURPLN exchange rate distributions across the analyzed months. This confirms that the previously observed differences are not an artifact of potential deviations from the normality assumption, but rather reflect real and statistically significant changes in the currency rate level during the second half of 2025. Mirroring the ANOVA results, the high chi-squared statistic indicates a strong influence of the time factor (month) on exchange rate volatility.\n\n***\n\n# Multiple Regression Modeling in the Forex Market\n\nUsing linear regression on data from the last four months (January to April 2026), determine the relationships of:  \n- the EURPLN exchange rate relative to the USDPLN, GBPPLN, AUDPLN, and JPYPLN exchange rates,  \n- the KGHM (KGH) stock price relative to the EURPLN, USDPLN, GBPPLN, AUDPLN, and JPYPLN exchange rates.  \nEvaluate the significance of each explanatory variable in the constructed models. Assume a significance level of $\\alpha = 0.05$.  \n\n## Data Preparation and Retrieval\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Setting the date range for the first four months of 2026\ndateStart2 <- as.Date(\"2026-01-01\")\ndateEnd2 <- as.Date(\"2026-04-30\")\n\n# List of symbols to download\nsymbols <- c('EURPLN', 'USDPLN', 'GBPPLN', 'AUDPLN', 'JPYPLN', 'KGH')\n\n# Fetching data using the previously defined read_rates function\ndata_list <- lapply(symbols, function(s) read_rates(s, dateStart2, dateEnd2))\n\n# Merging all data frames into a single data frame by the Date column\ndf_reg <- Reduce(function(x, y) merge(x, y, by = \"Date\"), data_list)\n```\n:::\n\n\n## Linear Regression\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Model 1: Relationship of the EURPLN rate relative to other currencies\nmodel_eur <- lm(EURPLN ~ USDPLN + GBPPLN + AUDPLN + JPYPLN, data = df_reg)\nsummary(model_eur)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = EURPLN ~ USDPLN + GBPPLN + AUDPLN + JPYPLN, data = df_reg)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.020873 -0.004665 -0.001045  0.004684  0.018486 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  2.24351    0.14581  15.387  < 2e-16 ***\nUSDPLN       0.23745    0.02930   8.105 6.38e-12 ***\nGBPPLN       0.12323    0.04673   2.637   0.0101 *  \nAUDPLN       0.13492    0.01736   7.770 2.82e-11 ***\nJPYPLN       8.33776    4.20687   1.982   0.0511 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.00754 on 77 degrees of freedom\nMultiple R-squared:  0.9255,\tAdjusted R-squared:  0.9217 \nF-statistic: 239.3 on 4 and 77 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\n# Model 2: Relationship of the KGHM stock price relative to exchange rates\nmodel_kgh <- lm(KGH ~ EURPLN + USDPLN + GBPPLN + AUDPLN + JPYPLN, data = df_reg)\nsummary(model_kgh)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = KGH ~ EURPLN + USDPLN + GBPPLN + AUDPLN + JPYPLN, \n    data = df_reg)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-32.195  -9.524   0.427   9.927  36.430 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   2044.94     573.95   3.563 0.000637 ***\nEURPLN        -168.55     222.23  -0.758 0.450519    \nUSDPLN        -267.93      77.77  -3.445 0.000932 ***\nGBPPLN          52.81      95.16   0.555 0.580513    \nAUDPLN          71.80      45.23   1.587 0.116558    \nJPYPLN      -21480.08    8410.28  -2.554 0.012650 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 14.7 on 76 degrees of freedom\nMultiple R-squared:  0.6445,\tAdjusted R-squared:  0.6211 \nF-statistic: 27.56 on 5 and 76 DF,  p-value: 8.355e-16\n```\n\n\n:::\n:::\n\n\n## Significance Assessment of Variables\n\n**Commentary on the EURPLN Model:**\nBased on the performed linear regression and the analysis of the $p$-values (Pr(>|t|)) at the significance level of $\\alpha = 0.05$, we can conclude that:\n\n* The variables that have a statistically significant effect on the EURPLN exchange rate are **USDPLN** ($p = 6.38 \\cdot 10^{-12}$), **GBPPLN** ($p = 0.0101$), and **AUDPLN** ($p = 2.82 \\cdot 10^{-11}$).\n* The JPYPLN exchange rate ($p = 0.0511$) lies on the verge of significance; however, under a strict assumption of $\\alpha = 0.05$, we do not consider it a significant variable in this specific model.\n* The Adjusted Coefficient of Determination ($Adjusted R^2$) is **0.9217**, meaning that the model explains 92.17% of the variance in the Euro exchange rate relative to the Polish złoty in the analyzed period, demonstrating an excellent model fit.\n\n**Commentary on the KGH Model:**\nAnalysis of the regression model for KGHM stock indicates that:\n\n* The significant explanatory variables ($p < 0.05$) for the KGHM stock price are **USDPLN** ($p = 0.000932$) and **JPYPLN** ($p = 0.012650$).\n* For the US Dollar, a **negative impact** on the company's valuation was observed (Estimate coefficient $\\approx -267.93$). This indicates that an increase in the USDPLN rate (depreciation of the Polish złoty against the Dollar) is statistically associated with a decline in KGHM stock prices during the analyzed period.\n* Other currencies, including the EURPLN rate ($p = 0.4505$), do not show any statistically significant impact on the company's stock price.\n* The Adjusted Coefficient of Determination ($Adjusted R^2$) of **0.6211** suggests a moderate fit of the model—currency factors explain approximately 62% of the variance in the KGHM price. This suggests a strong influence of non-currency factors, such as global copper prices or general stock market sentiment.\n\n***\n\n# Development and Evaluation of Predictive Sales Models\n\nThe file sprzedaz.txt contains data on a company's advertising expenses (in thousands of PLN) and the sales value of its products (in millions of PLN) across various quarters.  \n- Using linear regression, determine the relationship between sales value and advertising expenses. Plot the data points and the regression line on a single chart.  \n- Calculate the forecasted sales values if advertising expenses are 300, 500, and 700 thousand PLN. Estimate the standard deviation of the error associated with the forecasted sales values for each level of advertising expenses.  \n- For the data in the sprzedaz.txt file, investigate whether a quadratic relationship would provide a better model for the dependency between advertising expenses (in thousands of PLN) and sales value (in millions of PLN). Compare the values of the coefficient of determination $R^2$ for both models. Plot the corresponding line representing this relationship on the chart containing the data and the linear regression line determined in the previous step.  \n\n## Linear Regression Plot\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Loading data\nsales <- read.csv(\"data/sprzedaz.txt\")\n\n# Linear regression model\nlin_model <- lm(Income ~ Advert, data = sales)\n\n# Scatter plot with regression line\nplot(sales$Advert, sales$Income, \n     xlab = \"Advertising expenses [thousand PLN]\", \n     ylab = \"Sales value [million PLN]\", \n     main = \"Relationship between Sales and Advertising Expenses\",\n     pch = 19, col = \"blue\")\nabline(lin_model, col = \"red\", lwd = 2)\nlegend(\"topleft\", legend = \"Regression line\", col = \"red\", lwd = 2)\n```\n\n::: {.cell-output-display}\n![](lab4_files/figure-html/unnamed-chunk-9-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n## Forecasting and Prediction Error (300, 500, 700 thousand PLN)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnew_data <- data.frame(Advert = c(300, 500, 700))\nlin_pred <- predict(lin_model, newdata = new_data, se.fit = TRUE)\n\n# Calculating the standard deviation of the prediction error for an individual observation\n# Prediction error accounts for the mean estimation error and the residual variance\nse_pred_error <- sqrt(lin_pred$se.fit^2 + lin_pred$residual.scale^2)\n\n# Compiling the forecast results\nforecast_results <- data.frame(\n  Advertising_Expenses = new_data$Advert,\n  Forecasted_Sales = lin_pred$fit,\n  Prediction_Error_Estimate = se_pred_error\n)\nprint(forecast_results)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Advertising_Expenses Forecasted_Sales Prediction_Error_Estimate\n1                  300         9.574201                 0.6388024\n2                  500        12.502700                 0.6250514\n3                  700        15.431199                 0.6768939\n```\n\n\n:::\n:::\n\n\n## Quadratic Model and Statistical Verification\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nquad_model <- lm(Income ~ Advert + I(Advert^2), data = sales)\n\n# 1. Comparison of R^2 and Adjusted R^2\nsum_lin <- summary(lin_model)\nsum_quad <- summary(quad_model)\n\nr2_lin <- sum_lin$r.squared\nr2_adj_lin <- sum_lin$adj.r.squared\n\nr2_quad <- sum_quad$r.squared\nr2_adj_quad <- sum_quad$adj.r.squared\n\n# 2. ANOVA Test - checking if the addition of the quadratic term is significant\ntest_anova <- anova(lin_model, quad_model)\np_value_anova <- test_anova$\"Pr(>F)\"[2]\n\n# Displaying the comparison results\nstat_comparison <- data.frame(\n  Model = c(\"Linear\", \"Quadratic\"),\n  R_Squared = c(r2_lin, r2_quad),\n  Adj_R_Squared = c(r2_adj_lin, r2_adj_quad)\n)\nprint(stat_comparison)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      Model R_Squared Adj_R_Squared\n1    Linear 0.9140610     0.9095379\n2 Quadratic 0.9326505     0.9251672\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nANOVA test result (p-value for change):\", p_value_anova)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nANOVA test result (p-value for change): 0.03879825\n```\n\n\n:::\n\n```{.r .cell-code}\n# 3. Comparative plot\nplot(sales$Advert, sales$Income, \n     xlab = \"Advertising expenses [thousand PLN]\", \n     ylab = \"Sales value [million PLN]\", \n     main = \"Comparison of Linear and Quadratic Models\",\n     pch = 19, col = \"blue\")\nabline(lin_model, col = \"red\", lwd = 2)\n\n# Adding the quadratic model curve\nx_grid <- seq(min(sales$Advert), max(sales$Advert), length.out = 100)\ny_quad <- predict(quad_model, newdata = data.frame(Advert = x_grid))\nlines(x_grid, y_quad, col = \"darkgreen\", lwd = 2)\n\nlegend(\"topleft\", \n       legend = c(\"Data\", \"Linear Regression\", \"Quadratic Regression\"), \n       col = c(\"blue\", \"red\", \"darkgreen\"), \n       pch = c(19, NA, NA), \n       lwd = c(NA, 2, 2))\n```\n\n::: {.cell-output-display}\n![](lab4_files/figure-html/unnamed-chunk-11-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n## Conclusions and Analysis\n\n**Forecasted Sales Values:**\nBased on the linear model, the following sales forecasts (in millions of PLN) were determined for the given advertising expenses (in thousands of PLN):\n- For expenses of **300 thousand PLN**: the forecast is **9.57 million PLN** (standard deviation of the prediction error: 0.64).  \n- For expenses of **500 thousand PLN**: the forecast is **12.5 million PLN** (standard deviation of the prediction error: 0.63).  \n- For expenses of **700 thousand PLN**: the forecast is **15.43 million PLN** (standard deviation of the prediction error: 0.68).  \n\n**Comparison and Model Selection:**\n\nTo eliminate the risk of overfitting and confirm the validity of the model selection, an in-depth analysis was conducted:\n\n1.  **Adjusted Coefficient of Determination ($R^2$):** An increase was observed from **0.9095** (linear model) to **0.9252** (quadratic model). Since the adjusted coefficient accounts for the number of parameters, its increase unambiguously confirms that the non-linear model describes the data structure better, rather than merely fitting the noise.\n2.  **ANOVA Test:** Comparing both models with an F-test revealed a significant difference ($p = 0.0388$). Since the $p$-value is substantially smaller than the adopted significance level of 0.05, we reject the hypothesis that the linear model is sufficient.\n3.  **Visual Conclusions:** The plot confirms that the linear regression line (red) systematically deviates from the data at extreme levels of advertising expenses, whereas the quadratic curve (green) naturally tracks the slight arc formed by the data points.\n\n**Summary:** All applied statistical criteria confirm that the **quadratic model is more adequate and statistically justified**. The higher precision of this model stems from the non-linear nature of the relationship between advertising and sales in this specific dataset.\n",
    "supporting": [
      "lab4_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}