{
  "hash": "fcaf51d8123260cfe16ec11e65e1da54",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Parameter Estimation and Probability Distributions\"\nauthor: \"Michał Janiga\"\n---\n\n\n::: {.cell}\n\n:::\n\n\n# Modeling Traffic Flow Intensity\n\nThe Poisson distribution is frequently used to model traffic flow (with low intensity). The file skrety.txt contains the number of vehicles turning right at a certain intersection within three hundred 3-minute time intervals (the data were collected at different times of the day).  \n\n- Load the data using the command scan('skrety.txt').  \n- Fit a Poisson distribution to the data, i.e., estimate the parameter $\\lambda$ of the Poisson distribution, and record its value in the report.  \n- Verify and describe the consistency of the distribution with the estimated parameter $\\lambda$ against the registered data by graphically comparing the empirical and theoretical probability functions. Use the table() and\\ dpois() functions analogously to Example 4 in Project 1.  \n- Use the non-parametric bootstrap method to estimate the standard deviation of the estimator of the parameter $\\lambda$, and record its value in the report.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1. Data loading\ntraffic_data <- scan('data/skrety.txt')\n\n# 2. Estimation of the lambda parameter (sample arithmetic mean)\n# - represents both the expected value and variance\nlambda_est <- mean(traffic_data)\n\n# 3. Graphical consistency; empirical vs theoretical\n# Empirical frequency (percentage share of each number of cars)\nempirical_table <- table(traffic_data) / length(traffic_data)\n\n# Preparing the range\nx_axis <- 0:max(traffic_data)\n\n# Theoretical probability from the Poisson distribution\ntheoretical_prob <- dpois(x_axis, lambda = lambda_est)\n\n# Comparative plot\nplot(empirical_table, type = \"h\", lwd = 2, col = \"blue\", \n     main = \"Empirical vs Theoretical Probability Mass Function\",\n     xlab = \"Number of vehicles\", ylab = \"Probability\")\npoints(x_axis, theoretical_prob, col = \"red\", pch = 16)\nlines(x_axis, theoretical_prob, col = \"red\", lty = 2)\nlegend(\"topright\", legend = c(\"Empirical\", \"Theoretical (Poisson)\"), \n       col = c(\"blue\", \"red\"), lty = c(1, 2), pch = c(NA, 16))\n```\n\n::: {.cell-output-display}\n![](lab2_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# 4. Non-parametric bootstrap (resampling with replacement directly from the dataset)\nB <- 1000\nboot_lambdas <- replicate(B, mean(sample(traffic_data, replace = TRUE)))\nsd_boot <- sd(boot_lambdas)\n```\n:::\n\n\n- Estimated parameter lambda (lambda_est) for the Poisson distribution = 3.793\n- Standard deviation of the estimator (sd_boot) = 0.129\n\n**Conclusions**:\nUsing the non-parametric bootstrap method with B = 1000 replications, the standard error of the lambda estimator ($\\lambda$) was determined. The obtained value of approximately 0.129 indicates a high precision of estimation given the sample size n = 300. This means that 300 time intervals constitute a sufficiently large sample to trust the result.\n\n***\n\n# Analysis of Rates of Return for KGHM\n\n- For one selected company listed on the Warsaw Stock Exchange (GPW), calculate the percentage changes of the highest daily prices (Najwyzszy) over the last year and plot their histogram.  \n- Estimate the mean and variance of the percentage changes of the highest prices for the selected company, and record these values in the report.  \n- Based on the histogram and the probability density function plot determined for the estimated parameters (mean and variance), roughly verify whether we can assume that the percentage changes of the highest daily prices follow a normal distribution.  \n- Assuming that the changes of the highest daily prices follow a normal distribution, determine the 90%, 95%, and 99% confidence intervals for the mean and variance of the percentage changes of the highest daily prices for the selected company. Compare the results obtained for different confidence intervals.  \n\nDownloading and preparing data for KGHM:\n\n::: {.cell}\n\n```{.r .cell-code}\nTicker <- 'KGH'\n\nif (file.exists(\".env\")) readRenviron(\".env\")\napikey <- Sys.getenv(\"STOOQ_API_KEY\")\n\nwebLink <- paste0('https://stooq.pl/q/d/l/?s=', Ticker, \n                 '&i=d', '&apikey=', apikey)\nfile_path <- paste0(\"data/\", Ticker, \".csv\")\nif (!file.exists(file_path)) {\n  download.file(webLink, file_path, quiet = TRUE)\n}\ndf_KGH <- read.csv(file_path)\ndf_KGH$Data <- as.Date(df_KGH$Data)\n\n# Restricting data to the last year\ndf_KGH_year <- df_KGH[which(df_KGH$Data >= (Sys.Date() - 365)),]\n\n# Calculating percentage changes of the high prices\nn_kgh <- nrow(df_KGH_year)\ndf_KGH_year$High_pct_change <- c(NA, 100 * diff(df_KGH_year$Najwyzszy) / \n                         df_KGH_year$Najwyzszy[-n_kgh])\n\ndf_KGH_year = df_KGH_year[!is.na(df_KGH_year$High_pct_change),]\n```\n:::\n\n\nParameter estimation:\n\n::: {.cell}\n\n```{.r .cell-code}\nn_kgh <- nrow(df_KGH_year)\nmean_kgh <- mean(df_KGH_year$High_pct_change)\nvar_kgh <- var(df_KGH_year$High_pct_change)\nsd_kgh <- sd(df_KGH_year$High_pct_change)\n```\n:::\n\nThe estimated mean value is 0.1466 %, and the variance is 13.577 %.\n\nVerification of distribution \"normality\":\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(df_KGH_year$High_pct_change, breaks = 30, prob = TRUE, \n     main = \"Histogram of High Price Changes (KGHM)\",\n     xlab = \"Percentage change [%]\", ylab = \"Density\")\ncurve(dnorm(x, mean = mean_kgh, sd = sd_kgh), add = TRUE, col = \"red\", lwd = 2)\ngrid()\n```\n\n::: {.cell-output-display}\n![](lab2_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nThe histogram suggests that the distribution is close to normal (symmetric, bell-shaped), although there are \"fat tails\" and a higher concentration around the mean than in the ideal theoretical distribution. The theoretical normal distribution underestimates the frequency of events with small changes in the highest price. Additionally, the theoretical distribution underestimates extreme events, i.e., theoretical indications suggest a virtually zero probability of such an event occurring, whereas in reality they do occur and can determine the success of an investment. In short: the normal distribution does not account for extreme events.\n\n**Confidence intervals for the mean and variance**:\n\n::: {.cell}\n\n```{.r .cell-code}\nconf_levels = c(0.90, 0.95, 0.99)\nresults_mean = data.frame(Level = conf_levels, Lower = NA, Upper = NA)\nresults_var = data.frame(Level = conf_levels, Lower = NA, Upper = NA)\n\nfor(i in 1:length(conf_levels)) {\n  gamma = conf_levels[i]\n  \n  # Interval for the mean (Student's t-distribution, as estimates are from the sample)\n  w = sd_kgh * qt((1 + gamma)/2, n_kgh - 1) / sqrt(n_kgh)\n  results_mean[i, 2:3] = c(mean_kgh - w, mean_kgh + w)\n  \n  # Interval for the variance (chi-squared distribution, as variance cannot be negative)\n  a = (1 - gamma)/2\n  b = (1 - gamma)/2\n  results_var[i, 2:3] = c((n_kgh - 1) * var_kgh / qchisq(1 - b, n_kgh - 1),\n                           (n_kgh - 1) * var_kgh / qchisq(a, n_kgh - 1))\n}\n```\n:::\n\n\n**Confidence intervals for the mean value**:\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n  Level      Lower     Upper\n1  0.90 -0.5347422 0.8278794\n2  0.95 -0.6681851 0.9613223\n3  0.99 -0.9337402 1.2268774\n```\n\n\n:::\n:::\n\n\n**Confidence intervals for the variance**:\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n  Level     Lower    Upper\n1  0.90 10.661226 17.98532\n2  0.95 10.186390 19.00437\n3  0.99  9.337606 21.22570\n```\n\n\n:::\n:::\n\n\n**Conclusions**:\nAs the confidence level increases (from 90% to 99%), the width of the confidence intervals increases, which is consistent with theory – to have greater confidence that the parameter lies within the interval, we must widen that interval. It should be noted that a useful value for an investor or manager would be to use the standard deviation, which operates in real units. Thus, the risk measure, eg. volatility, remains a factor of individual assessment or can be used to set the position size in a portfolio targeting pre-determined return-to-risk parameters.\n\n**Conclusions cont.**:\nAlthough the determined confidence intervals for the mean and variance allow for a mathematical description of KGHM's stock price volatility, their decision-making value in a long-term investment strategy is limited. Statistics only describe historical price behavior (symptoms) without delving into the company's business model (causes). For a fundamental investor, the health of the company remains crucial, whereas variance analysis serves only for technical adjustment of the acceptable portfolio fluctuation level (volatility management rather than value management).\n\n***\n\n# Bayesian Inference\n\nA tossed thumbtack lands point-down or point-up. This experiment can be described by a Bernoulli distribution with parameter $p$ representing the probability of the thumbtack landing point-up. \n\nThe distribution of the parameter $p$ can be described by a Beta distribution with parameters $\\alpha$ and $\\beta$. The mean and variance in\\ a Beta distribution depend on the parameters of the distribution in the following way:\n$$ \\mathbb{E}X = \\frac{\\alpha}{\\alpha + \\beta}, \\qquad \\mathbb{V}X = \\frac{\\alpha\\beta}{(\\alpha + \\beta)^2(\\alpha + \\beta + 1)}, \\qquad mode = \\frac{\\alpha - 1}{\\alpha + \\beta - 2}.$$\n\n* Based on the hypothesized (prior) expected value of the parameter $p$, propose values for the parameters $\\alpha$ and $\\beta$ of the prior distribution of parameter $p$. Draw the prior distribution of parameter $p$ (use the dbeta() function).  \n* Toss the thumbtack 20 times and record the results of subsequent tosses (1 - thumbtack lands point-up, 0 - thumbtack lands point-down). Determine and plot the posterior distribution of parameter $p$ and calculate the value of the Bayesian estimator $\\hat{p}$. In\\ the case under consideration, the posterior distribution of parameter $p$ is also a Beta distribution with parameters:\n$$ \\alpha_{\\textrm{post}} = \\alpha_{\\textrm{prior}} + \\sum_{i=1}^n x_i, \\qquad \\beta_{\\textrm{post}} = \\beta_{\\textrm{prior}} + n - \\sum_{i=1}^n x_i,\\qquad x_i\\in\\{0,1\\}.$$  \n* Toss the thumbtack another 20 times and record the results. Determine and plot the posterior distribution based on all 40 tosses and calculate the value of the Bayesian estimator $\\hat{p}$ in this case. Compare the results with those obtained after the first 20 tosses.  \n* Using the formula for the variance of the Beta distribution, determine and compare the variances of the prior distribution, posterior after 20 tosses, and posterior after 40 tosses.  \n\nPrior parameters proposal:\nWe assume that $p \\approx 0.4$. We adopt $\\alpha_{prior} = 4$ and $\\beta_{prior} = 6$.  \nThen $\\mathbb{E}p = 4 / (4+6) = 0.4$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Let the \"strength\" of belief be 10 (the sample size indicates low certainty)\nalpha_prior = 4  # successes\nbeta_prior = 6   # failures\n\ncurve(dbeta(x, alpha_prior, beta_prior), from = 0, to = 1,\n      main = \"Prior distribution (Beta)\", xlab = \"p\", ylab = \"f(p)\",\n      col = \"red\", lwd = 2)\ngrid()\n```\n\n::: {.cell-output-display}\n![](lab2_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nSimulation of the first 20 tosses and determination of the posterior distribution:\n(We simulate tosses with probability $p = 0.35$)\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\nn1 = 20\nx1 = rbinom(n1, 1, 0.35)  # toss simulation\ns1 = sum(x1)  # sum of successes\n\nalpha_post1 = alpha_prior + s1\nbeta_post1 = beta_prior + n1 - s1\n\n# Bayesian estimator - expected value of the posterior distribution\np_hat1 = alpha_post1 / (alpha_post1 + beta_post1)  # updating p\n```\n:::\n\n\nIn the first 20 tosses, 8 successes were obtained.\nPosterior parameters (n=20): $\\alpha_{post1}$ = 12, $\\beta_{post1}$ = 18.\nBayesian estimator $\\hat{p}_{20}$ = 0.4.\n\nSimulation of the next 20 tosses (40 total):\n\n::: {.cell}\n\n```{.r .cell-code}\nn2 = 20\nx2 = rbinom(n2, 1, 0.35)\ns2 = sum(x2)\n\n# Accumulating observations\ns_total = s1 + s2\nn_total = n1 + n2\n\nalpha_post2 = alpha_prior + s_total\nbeta_post2 = beta_prior + n_total - s_total\np_hat2 = alpha_post2 / (alpha_post2 + beta_post2)\n```\n:::\n\n\nIn a total of 40 tosses, 18 successes were obtained.\nPosterior parameters (n=40): $\\alpha_{post2}$ = 22, $\\beta_{post2}$ = 28.\nBayesian estimator $\\hat{p}_{40}$ = 0.44.\n\nComparison plot:\n\n::: {.cell}\n\n```{.r .cell-code}\ncurve(dbeta(x, alpha_post2, beta_post2), from = 0, to = 1, col = \"green\", lwd = 2,\n      main = \"Comparison of distributions\", xlab = \"p\", ylab = \"f(p)\")\ncurve(dbeta(x, alpha_post1, beta_post1), add = TRUE, col = \"blue\", lwd = 2)\ncurve(dbeta(x, alpha_prior, beta_prior), add = TRUE, col = \"red\", lwd = 2, lty = 2)\nlegend(\"topright\", legend = c(\"Prior\", \"Posterior (n=20)\", \"Posterior (n=40)\"),\n       col = c(\"red\", \"blue\", \"green\"), lty = c(2, 1, 1), lwd = 2)\ngrid()\n```\n\n::: {.cell-output-display}\n![](lab2_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\nVariance comparison:\n\n::: {.cell}\n\n```{.r .cell-code}\nvar_beta = function(a, b) (a * b) / ((a + b)^2 * (a + b + 1))\nv_prior = var_beta(alpha_prior, beta_prior)\nv_post1 = var_beta(alpha_post1, beta_post1)\nv_post2 = var_beta(alpha_post2, beta_post2)\n```\n:::\n\n\nPrior variance: 0.021818.\nPosterior variance (n=20): 0.007742.\nPosterior variance (n=40): 0.004831.\n\n**Conclusions**: As the number of tosses increases (from 0 to 20 and 40), the variance of the distribution of parameter $p$ decreases, which indicates an increase in certainty regarding the estimated probability value. The distribution becomes more \"concentrated\" around the true value.\n\n***\n\n# Analysis of Photon Registration Intervals\n\nThe file fotony.txt contains intervals between registration times of consecutive gamma-ray photons captured by the Compton Gamma Ray Observatory (CGRO) space telescope in 1991.\n\n- Load the data using the command scan('fotony.txt')  \n- Using the method of moments and the maximum likelihood method, determine the estimates of the gamma distribution parameters corresponding to the registered data. Compare the results obtained for both methods.  \n- On a single plot, draw the histogram of intervals and the probability density functions of the gamma distribution with parameters estimated using both methods.  \n- Using the parametric bootstrap method, determine the standard deviations of the gamma distribution parameter estimators ($\\alpha$ and $\\beta$) and their 95% confidence intervals for both methods (moments and maximum likelihood). Compare the results obtained for both methods.  \n\nData loading:\n\n::: {.cell}\n\n```{.r .cell-code}\nphotons_path = 'data/fotony.txt'\nphotons_x = scan(photons_path)\nphotons_n = length(photons_x)\n```\n:::\n\n\nMethod of Moments (MoM):\n\n::: {.cell}\n\n```{.r .cell-code}\n# We assume that the sample characteristics should correspond to the theoretical characteristics of the model\nm1 = mean(photons_x)\nm2 = mean(photons_x^2)\n\n# Thus the variance will be: m2 - m1^2\nalpha_mom = m1^2 / (m2 - m1^2)\nbeta_mom = (m2 - m1^2) / m1\n```\n:::\n\nMoM Estimates: $\\hat{\\alpha}$ = 1.0655, $\\hat{\\beta}$ = 73.6241.\n\nMaximum Likelihood Estimation (MLE):\n\n::: {.cell}\n\n```{.r .cell-code}\n# Likelihood equation (derivative = 0)\nfun_mle = function(a) digamma(a) - log(a) - mean(log(photons_x)) + \n  log(mean(photons_x))\n\n# Searching for the optimal alpha (peak)\n# The interval results from the previously calculated alpha size\nalpha_mle = uniroot(fun_mle, lower = 0.1, upper = 10)$root\nbeta_mle = mean(photons_x) / alpha_mle\n```\n:::\n\nMLE Estimates: $\\hat{\\alpha}$ = 1.052, $\\hat{\\beta}$ = 74.5736.\n\n**Conclusion**:\nThe estimated shape parameter $\\hat{\\alpha}$ indicates that the photon registration process by the CGRO telescope is close to a Poisson process (exponential distribution), which is consistent with the physical nature of gamma radiation registration. The obtained scale $\\hat{\\beta}$ allows for precise determination of the intensity of this radiation during the studied period.\n\nGraphical comparison:\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(photons_x, breaks = 50, prob = TRUE, main = \"Histogram of photon intervals\",\n     xlab = \"Time interval\", ylab = \"Density\")\ncurve(dgamma(x, shape = alpha_mom, scale = beta_mom), add = TRUE, \n      col = \"blue\", lwd = 2)\ncurve(dgamma(x, shape = alpha_mle, scale = beta_mle), add = TRUE, \n      col = \"red\", lwd = 2, lty = 2)\nlegend(\"topright\", legend = c(\"MoM\", \"MLE\"), col = c(\"blue\", \"red\"), \n       lty = c(1, 2), lwd = 2)\ngrid()\n```\n\n::: {.cell-output-display}\n![](lab2_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n**Conclusions**:\nVisual analysis of the histogram and the overlaid Gamma densities estimated using the MoM and MLE methods confirms the high quality of the model fit. The negligible differences between the two estimation methods and the close fit of the curves to the empirical data suggest that the parameters $\\hat{\\alpha}$ and $\\hat{\\beta}$ were estimated reliably, and the Gamma distribution correctly captures the characteristics of the intervals between photon registrations.\n\nParametric bootstrap:\n\n::: {.cell}\n\n```{.r .cell-code}\nK = 1000\nboot_results = replicate(K, {\n  # For MoM\n  boot_data_mom = rgamma(photons_n, shape = alpha_mom, scale = beta_mom)\n  bm1 = mean(boot_data_mom); bm2 = mean(boot_data_mom^2)\n  b_alpha_mom = bm1^2 / (bm2 - bm1^2)\n  b_beta_mom = (bm2 - bm1^2) / bm1\n  \n  # For MLE\n  boot_data_mle = rgamma(photons_n, shape = alpha_mle, scale = beta_mle)\n  b_alpha_mle = uniroot(function(a) digamma(a) - log(a) -\n                          mean(log(boot_data_mle)) + log(mean(boot_data_mle)),\n                        lower = 0.1, upper = 10)$root\n  b_beta_mle = mean(boot_data_mle) / b_alpha_mle\n  \n  c(b_alpha_mom, b_beta_mom, b_alpha_mle, b_beta_mle)\n})\n\nsd_results = apply(boot_results, 1, sd)\nconf_intervals_results = apply(boot_results, 1, quantile, probs = c(0.025, 0.975))\n\nresults_tab = data.frame(\n  Method = c(\"MoM alpha\", \"MoM beta\", \"MLE alpha\", \"MLE beta\"),\n  Estimate = c(alpha_mom, beta_mom, alpha_mle, beta_mle),\n  SD_boot = sd_results,\n  ConfInterval_2.5 = conf_intervals_results[1,],\n  ConfInterval_97.5 = conf_intervals_results[2,]\n)\n```\n:::\n\n\nParametric bootstrap results:\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n     Method  Estimate    SD_boot ConfInterval_2.5 ConfInterval_97.5\n1 MoM alpha  1.065542 0.03301125         1.005232          1.132223\n2  MoM beta 73.624064 2.57559857        68.866734         78.804513\n3 MLE alpha  1.051974 0.02035316         1.013378          1.093801\n4  MLE beta 74.573635 1.83656352        70.866948         78.007241\n```\n\n\n:::\n:::\n\n\nStatistical analysis of intervals between photons demonstrated that the Gamma distribution model is highly stable. Comparison of estimation methods indicates the advantage of the Maximum Likelihood Estimation (MLE) method, which provided estimators with a lower standard error ($SD_{\\alpha} = 0.020$) and narrower 95% confidence intervals compared to the Method of Moments. The determined confidence intervals for the shape parameter $\\alpha$ (MLE: $[1.013; 1.094]$) allow us to reject the hypothesis of a purely exponential nature of the distribution ($\\alpha = 1$) at a significance level of $0.05$. The process has a subtle structure that cannot be explained by a simple exponential distribution.\n\n***\n",
    "supporting": [
      "lab2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}