{
  "hash": "1040f6faf8bdeb8aff1b1580c4f0b28a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Statistical Hypothesis Testing\"\nauthor: \"Michał Janiga\"\n---\n\n\n::: {.cell}\n\n:::\n\n\n# Analysis of Mean Values for Medical Data\n\nThe file tempciala.txt contains recorded values of heart rate and body temperature for 65 men (gender = 1) and 65 women (gender = 2).\n\nSeparately for men and women:\n\n* estimate the mean and standard deviation of temperature,\n\n* verify at the significance level $\\alpha = 0.05$ the hypothesis that the mean temperature is equal to 36.6 $^\\circ$C against the alternative hypothesis that the mean temperature is different, assuming that the temperatures have a normal distribution and the variance of the distribution is unknown.\n\nSince the variance of the distribution is unknown as indicated in the task, it should be estimated based on the sample standard deviation.\n Student's t-test provides a wider \"width\" of the normal distribution, allowing for safer inference with an unknown variance.\n\nThe `t.test` function requires the investigated characteristic to have a normal distribution. This is satisfied by the task description.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load data\ntemp_data <- read.csv(\"data/tempciala.txt\")\nnames(temp_data) <- c(\"temperature\", \"gender\", \"heart_rate\")\n\n# Split into groups\nmen_temp <- temp_data$temperature[temp_data$gender == 1]\nwomen_temp <- temp_data$temperature[temp_data$gender == 2]\n\n# Parameter estimation\nmean_men <- mean(men_temp)\nsd_men <- sd(men_temp)\nmean_women <- mean(women_temp)\nsd_women <- sd(women_temp)\n\n# Display estimation results\ndata.frame(\n  Gender = c(\"Men\", \"Women\"),\n  Mean = c(mean_men, mean_women),\n  Std_dev = c(sd_men, sd_women)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Gender     Mean   Std_dev\n1    Men 36.72615 0.3882158\n2  Women 36.88923 0.4127359\n```\n\n\n:::\n\n```{.r .cell-code}\n# Hypothesis tests of hypothetical mean body temperature (H0: mu = 36.6)\n# By default, a two-sided test is performed\n# The confidence level resulting from the task is explicitly provided\nmen_test <- t.test(men_temp, conf.level = 0.95, mu = 36.6)\nwomen_test <- t.test(women_temp, conf.level = 0.95, mu = 36.6)\n\nmen_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  men_temp\nt = 2.6199, df = 64, p-value = 0.01097\nalternative hypothesis: true mean is not equal to 36.6\n95 percent confidence interval:\n 36.62996 36.82235\nsample estimates:\nmean of x \n 36.72615 \n```\n\n\n:::\n\n```{.r .cell-code}\nwomen_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  women_temp\nt = 5.6497, df = 64, p-value = 3.985e-07\nalternative hypothesis: true mean is not equal to 36.6\n95 percent confidence interval:\n 36.78696 36.99150\nsample estimates:\nmean of x \n 36.88923 \n```\n\n\n:::\n:::\n\n\n## Conclusions\n\nFor men, the estimated mean temperature is approx. 36.73 $^\\circ$C, and the standard deviation is approx. 0.39 $^\\circ$C. The p-value (0.011) is less than $\\alpha=0.05$, so we reject the null hypothesis $H_0$ in favor of the alternative. The mean temperature in men differs significantly from 36.6 $^\\circ$C.\n\nFor women, the estimated mean temperature is approx. 36.89 $^\\circ$C, and the standard deviation is approx. 0.41 $^\\circ$C. The p-value (3.985e-07) is significantly less than $\\alpha=0.05$, so we reject the null hypothesis $H_0$ in favor of the alternative. The mean temperature in women also differs significantly from 36.6 $^\\circ$C.\n\n***\n\n# Investigation of Seasonality of Phenomena\n\nThe table below contains data regarding the number of suicides in the United States in 1970, broken down by individual months.\n\n| Month       | Number of suicides | Number of days |\n| :---        |          :----:    |   :----:       |\n| January     | 1867               | 31             |\n| February    | 1789               | 28             |\n| March       | 1944               | 31             |\n| April       | 2094               | 30             |\n| May         | 2097               | 31             |\n| June        | 1981               | 30             |\n| July        | 1887               | 31             |\n| August      | 2024               | 31             |\n| September   | 1928               | 30             |\n| October     | 2032               | 31             |\n| November    | 1978               | 30             |\n| December    | 1859               | 31             |\n\nVerify at the significance level $\\alpha = 0.05$ whether the presented data indicate a constant intensity of the investigated phenomenon, or rather suggest seasonal variation in the number of suicides. Assume that in the case of a constant intensity, the number of suicides in a given month is proportional to the number of days in that month.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Data\nsuicides <- c(1867, 1789, 1944, 2094, 2097, 1981, 1887, 2024, 1928, 2032, 1978, 1859)\ndays_in_month <- c(31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31)\n\n# Hypothesis: number of suicides proportional to the number of days\n# Theoretical probabilities\ntheoretical_probs <- days_in_month / sum(days_in_month)\n\n# Chi-squared goodness-of-fit test\nseasonality_test <- chisq.test(x = suicides, p = theoretical_probs)\nseasonality_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tChi-squared test for given probabilities\n\ndata:  suicides\nX-squared = 47.365, df = 11, p-value = 1.852e-06\n```\n\n\n:::\n:::\n\n\n## Conclusions\n\nThe p-value (1.852011e-06) is significantly less than the significance level $\\alpha=0.05$. This means we reject the hypothesis of a constant intensity of suicides proportional to the number of days in the month. The data indicate the presence of seasonal variation in the number of suicides.\n\n***\n\n# Advanced Normality Tests of Financial Time Series\n\nFor a selected company listed on the Warsaw Stock Exchange (GPW), load data from the stooq.pl website, and then\n\n* calculate the percentage changes of the lowest prices on individual days over the last year, plot their histogram, and draw the probability density function of a normal distribution with parameters estimated based on their values,\n\n* applying various tests discussed in the examples, verify at the significance level $\\alpha = 0.05$ the hypothesis that the percentage changes of the lowest prices on individual days over the last year have a normal distribution.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(moments)\nlibrary(nortest)\n\n# Selected company: KGHM\nif (file.exists(\".env\")) readRenviron(\".env\")\napikey <- Sys.getenv(\"STOOQ_API_KEY\")\nticker <- 'KGH'\nurl <- paste0('https://stooq.pl/q/d/l/?s=', ticker, \n                 '&i=d', '&apikey=', apikey)\nfile_path <- paste0(\"data/\", ticker, \".csv\")\nif (!file.exists(file_path)) {\n  download.file(url, file_path, quiet = TRUE)\n}\nkgh_df <- read.csv(file_path)\nnames(kgh_df)[names(kgh_df) == \"Data\"] <- \"Date\"\nnames(kgh_df)[names(kgh_df) == \"Najnizszy\"] <- \"Low\"\nkgh_df$Date <- as.Date(kgh_df$Date)\nkgh_year_df <- kgh_df[which(kgh_df$Date >= (Sys.Date() - 365)),]\nlow_prices <- kgh_year_df$Low\n\n# Calculation of percentage changes (vector method avoiding NA)\npct_changes <- diff(low_prices) / low_prices[-length(low_prices)] * 100\n\n# Parameters for normal distribution\nmu <- mean(pct_changes)\nsigma <- sd(pct_changes)\n\n# Histogram and density\nhist(pct_changes, breaks = 30, probability = TRUE, \n     main = paste(\"Histogram of percentage changes:\", ticker),\n     xlab = \"Percentage change [%]\", ylab = \"Density\", col = \"lightblue\")\ncurve(dnorm(x, mean = mu, sd = sigma), add = TRUE, col = \"red\", lwd = 2)\n```\n\n::: {.cell-output-display}\n![](lab3_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Normality tests\nshapiro_test <- shapiro.test(pct_changes)\nks_test <- ks.test(pct_changes, \"pnorm\", mean = mu, sd = sigma)\n# Tests from the \"moments\" library\nans_test <- anscombe.test(pct_changes)\nago_test <- agostino.test(pct_changes)\njb_test <- jarque.test(pct_changes)\nlillie_test <- lillie.test(pct_changes)\n\nshapiro_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  pct_changes\nW = 0.96276, p-value = 0.01876\n```\n\n\n:::\n\n```{.r .cell-code}\nks_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tExact one-sample Kolmogorov-Smirnov test\n\ndata:  pct_changes\nD = 0.080729, p-value = 0.637\nalternative hypothesis: two-sided\n```\n\n\n:::\n\n```{.r .cell-code}\nans_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAnscombe-Glynn kurtosis test\n\ndata:  pct_changes\nkurt = 5.4126, z = 2.9517, p-value = 0.003161\nalternative hypothesis: kurtosis is not equal to 3\n```\n\n\n:::\n\n```{.r .cell-code}\nago_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tD'Agostino skewness test\n\ndata:  pct_changes\nskew = -0.085543, z = -0.338092, p-value = 0.7353\nalternative hypothesis: data have a skewness\n```\n\n\n:::\n\n```{.r .cell-code}\njb_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tJarque-Bera Normality Test\n\ndata:  pct_changes\nJB = 19.743, p-value = 5.163e-05\nalternative hypothesis: greater\n```\n\n\n:::\n\n```{.r .cell-code}\nlillie_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tLilliefors (Kolmogorov-Smirnov) normality test\n\ndata:  pct_changes\nD = 0.080729, p-value = 0.2151\n```\n\n\n:::\n:::\n\n\n## Conclusions\n\nStatistical analysis of the percentage changes of the KGH stock price exhibits classic characteristics of financial time series. The results of the tests at the significance level $\\alpha = 0.05$ are as follows:\n\n1.  Rejection of normality: The Shapiro-Wilk test ($p = 1.876e-02$) and the Jarque-Bera test ($p = 5.163e-05$) unambiguously reject the null hypothesis $H_0$. \n2.  Cause of non-normality (leptokurtosis): The Anscombe-Glynn test shows high kurtosis at 5.41. The very low $p = 3.161e-03$ provides statistical evidence for the presence of \"heavy tails\".\n3.  Skewness: D'Agostino's test shows skewness at -0.086. The p-value $p = 0.7353$ is greater than $\\alpha$, meaning there are no grounds to reject the hypothesis of distribution symmetry.\n4.  KS test specificity: The Kolmogorov-Smirnov test ($p = 0.637$) is the only one that does not reject $H_0$. This confirms its lower sensitivity to tail anomalies compared to moment-based tests (JB, Anscombe). The test measures the maximum distance between cumulative distribution functions, which in this case oscillates around the area of highest probability density, explaining the above statement. Furthermore, the KS test could be somewhat overly optimistic due to estimating parameters from the sample – it is less likely to reject the hypothesis of non-normality even when the data are non-normal.\n5.  To \"update\" the KS test, an additional Lilliefors test was conducted using the \"nortest\" library. This test clearly indicates non-normality since $p = 2.151e-01$ clearly rejects the null hypothesis $H_0$.\n\nSummary: Since key tests (Shapiro-Wilk, Jarque-Bera) returned $p < \\alpha$, we assume that the price change distribution is not normal. The dominant feature is leptokurtosis, which means that the risk of extreme events is higher than in the theoretical model.\n\n***\n\n# Comparison of the Lifespan of Industrial Components\n\nThe file lozyska.txt contains the operating times (in millions of cycles) until failure of bearings made of two different materials.\n\n* Perform a test of no difference between the operating times of bearings made of different materials, assuming that the operating time until failure is described by a normal distribution, without assuming equal variances. Assume a significance level $\\alpha = 0.05$.\n\n* Perform an analogous test, without assuming normal distributions.\n\n* **(optional)** Estimate the probability that a bearing made of the first material will operate longer than a bearing made of the second material.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load data\nbearing_data <- read.csv(\"data/lozyska.txt\", quote = \"'\")\ntype1 <- bearing_data$Typ.I\ntype2 <- bearing_data$Typ.II\n\n# 1. Welch's t-test (assuming normality, not assuming equal variances)\nt_test <- t.test(type1, type2, var.equal = FALSE)\nt_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  type1 and type2\nt = 2.0723, df = 16.665, p-value = 0.05408\nalternative hypothesis: true difference in means is not equal to 0\n95 percent confidence interval:\n -0.07752643  7.96352643\nsample estimates:\nmean of x mean of y \n   10.693     6.750 \n```\n\n\n:::\n\n```{.r .cell-code}\n# 2. Wilcoxon test (without assuming normality)\nwilcox_test <- wilcox.test(type1, type2)\nwilcox_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon rank sum exact test\n\ndata:  type1 and type2\nW = 75, p-value = 0.06301\nalternative hypothesis: true location shift is not equal to 0\n```\n\n\n:::\n\n```{.r .cell-code}\n# 3. Estimating the probability P(X > Y)\n# We can do this by checking all pairs (x_i, y_j)\ncomparison_matrix <- outer(type1, type2, \">\")\np_hat <- mean(comparison_matrix)\np_hat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.75\n```\n\n\n:::\n:::\n\n\n## Conclusions\n\n- The result of Welch's t-test (p-value = 0.0541) at the significance level $\\alpha=0.05$ provides no grounds to reject the hypothesis of no difference between the mean bearing operating times (p-value > 0.05).\n- The result of the Wilcoxon test (p-value = 0.063) also does not allow rejecting the hypothesis of no difference between the distributions (p-value > 0.05).\n\nIn both cases, we assume that there are no statistically significant differences in the operating times of bearings made of different materials.\n\n**Additionally:** The estimated probability that a bearing made of the first material will operate longer than a bearing made of the second material is approximately 75%. Although Type I bearings operated longer than Type II bearings in 75% of cases, at the significance level $\\alpha = 0.05$, it was not possible to prove that this difference is permanent and reproducible. This suggests that Type I may be better in practice; however, to confirm this thesis with statistical certainty, further study with a larger sample size is required.\n\n***\n\n# Analysis of Statistical Independence in Sports\n\nUsing data from the pl.fcstats.com website, verify the hypothesis of independence of home team results (wins, draws, and losses) from the country in which the football matches are played. Assume a significance level $\\alpha = 0.05$.\n\n* Perform the tests based on data regarding the following leagues:\n\n    * German – Bundesliga (German league),\n    \n    * Polish – Ekstraklasa (Liga polska),\n    \n    * English – Premier League (English league),\n    \n    * Spanish – LaLiga (Liga hiszpańska).\n    \n* The data can be found in the \"Porównanie lig\" (League comparison) -> \"Zwycięzcy meczów\" (Match winners) tab, in columns (excluding the [%] sign):\n\n    * 1 – home wins, e.g., 125 for the German league (Bundesliga),\n    \n    * x – draws, e.g., 86 for the German league,\n    \n    * 2 – home losses, e.g., 95 for the German league.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Preparation of contingency table (2025/2026 season)\n# Rows: League, Columns: Result (win, draw, loss)\nresults <- matrix(c(\n  125, 86, 95,   # Bundesliga\n  108, 65, 67,   # Ekstraklasa\n  193, 96, 91,  # Premier League\n  194, 95, 91   # LaLiga\n), nrow = 4, byrow = TRUE)\n\nrownames(results) <- c(\"Bundesliga\", \"Ekstraklasa\", \"Premier League\", \"LaLiga\")\ncolnames(results) <- c(\"1\", \"X\", \"2\")\n\n# Display table\nresults\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 1  X  2\nBundesliga     125 86 95\nEkstraklasa    108 65 67\nPremier League 193 96 91\nLaLiga         194 95 91\n```\n\n\n:::\n\n```{.r .cell-code}\n# Chi-squared test of independence\nindependence_test <- chisq.test(results)\nindependence_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  results\nX-squared = 10.325, df = 6, p-value = 0.1116\n```\n\n\n:::\n:::\n\n\n## Conclusions\n\nThe p-value (0.1116) is greater than the significance level $\\alpha=0.05$. This means there are no grounds to reject the hypothesis of the independence of match results (wins, draws, and losses) from the country/league in which the matches are played. The 1, X, 2 statistics in the analyzed leagues are sufficiently close to each other to prevent finding significant differences.\n\n***\n",
    "supporting": [
      "lab3_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}